experiment:
  format: "md" # Options: "md", "txt"
  documents_dir: "../extract_docs" # Default base dir

embeddings:
  type: "local" # Options: "local", "api"
  model_name: "google/embeddinggemma-300m" # Quick default
  # For OpenRouter or OpenAI compatible API
  api_base: ""
  api_key: ""
  
llm:
  provider: "openrouter"
  model: "nvidia/nemotron-3-nano-30b-a3b:free"
  temperature: 0.3
