[theme]
base = "light"
primaryColor = "#1A1816"
backgroundColor = "#EDEAE3"
secondaryBackgroundColor = "#E5E2DA"
textColor = "#1A1816"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
